### ISSUE TITLE
Is the test split available?

### ISSUE THREAD

**Issue by ad12** [mylyu/M4Raw#1]
Thank you for your effort in releasing this dataset! It is an invaluable resource to the community.

The README for the parallel reconstruction demos mentions that we should expect to have 3 splits -- train, val, and test [link](https://github.com/mylyu/M4Raw/tree/main/parallel_imaging_demo/VarNet_demo#end-to-end-variational-networks-for-accelerated-mri-reconstruction-model). However, the zenodo link does not have a `multicoil_test` zip file. Is there another way we can access this file?

**Comment by mylyu** [comment]
> Thank you for your effort in releasing this dataset! It is an invaluable resource to the community.
> 
> The README for the parallel reconstruction demos mentions that we should expect to have 3 splits -- train, val, and test [link](https://github.com/mylyu/M4Raw/tree/main/parallel_imaging_demo/VarNet_demo#end-to-end-variational-networks-for-accelerated-mri-reconstruction-model). However, the zenodo link does not have a `multicoil_test` zip file. Is there another way we can access this file?

Thanks for your interest. We are inspecting the motion issue of the test subset (~30 subjects) and will release it in a few weeks. You may use the val subset for test subset for now.

**Comment by mylyu** [comment]
@ad12 Please note we have just released the test set: https://zenodo.org/record/8056074
